# Generated by Django 4.0 on 2022-08-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todoitem_date_todoitem_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
